spring:
  datasource:
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

admin:
  password: admin12
  email: admin@gmail.com
  firstname: admin
  lastname: account

jwt:
  secretKey: ${JWT_SECRET_KEY:defaultSecretKeyHere}

server:
  port: ${PORT:8080}
